services:
- type: web
  name: typesense
  repo: https://github.com/suleyunus/deploy-typesense-on-render.git
  plan: starter
  runtime: docker
  healthCheckPath: /health
  disk:
    name: typesense-data
    mountPath: /typesense-data
    sizeGB: 1  
  envVars:
  - key: TYPESENSE_API_KEY
    generateValue: true
  - key: TYPESENSE_DATA_DIR
    value: /typesense-data
  - key: TYPESENSE_ENABLE_CORS
    value: true